events { worker_connections 1024; }

http {
    # Define the group of servers to balance
    upstream auction_backend {
        least_conn; # Use least connections load balancing
        server backend1:8080;
        server backend2:8080;
    }

    server {
        listen 80;
        location /nginx_status {
                stub_status;
                allow 127.0.0.1;   # Only allow local requests for security
                allow all;         # For now, allow all for browser access
            }
        location / {
            proxy_pass http://auction_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}