spring.application.name=ApexBid

# Database configuration
# Default fallback credentials point to localhost for native execution
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/apexbid_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vaibhav_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#
spring.jpa.open-in-view=false

# Schema management
# Dynamically controlled via Docker environment blocks to avoid multi-instance execution collisions
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}

# Cache configuration
# Default fallback to localhost for native execution
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Logging
logging.level.org.springframework=INFO
logging.level.org.vaibhav.apexbid=DEBUG

# Enable Java 21 Virtual Threads globally
spring.threads.virtual.enabled=true

# --- REDIS KEYS ---
# Core / Infrastructure
redis.keys.system-state=system:state
redis.keys.cluster-lock=lock:cluster:coordinator

# Hash Prefixes
redis.keys.auction-hash-prefix=auction:
redis.keys.wallet-hash-prefix=wallet:

# Core ZSETs
redis.keys.auctions-upcoming=auctions:upcoming
redis.keys.auctions-active=auctions:active
redis.keys.auctions-highest-bids=auctions:highest_bids
redis.keys.auctions-most-active=auctions:most_active

# Settlement Phase
redis.keys.auctions-settlement-queue=auctions:settlement:queue
redis.keys.auctions-settlement-processing-zset=auctions:settlement:processing:zset

# Checkout Phase
redis.keys.auctions-checkout-queue=auctions:checkout:queue
redis.keys.auctions-checkout-processing-zset=auctions:checkout:processing:zset

# Pub/Sub Channels
redis.keys.channel-auction-updates=auction:updates
redis.keys.channel-wallet-updates=wallet:updates